CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR UNIQUE NOT NULL,
    user_name  VARCHAR        NOT NULL

);

CREATE TABLE IF NOT EXISTS categories
(
    category_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_annotation         VARCHAR NOT NULL,
    event_category_id        BIGINT NOT NULL,
    event_confirmed_requests INT DEFAULT 0,
    event_created_on         TIMESTAMP DEFAULT now(),
    event_description        VARCHAR NOT NULL,
    event_date               TIMESTAMP NOT NULL,
    event_initiator_id       BIGINT NOT NULL,
    event_location_lat       FLOAT NOT NULL,
    event_location_lon       FLOAT NOT NULL,
    event_paid               BOOLEAN DEFAULT false,
    event_participant_limit  INT DEFAULT 0,
    event_published_on       TIMESTAMP,
    event_request_moderation BOOLEAN DEFAULT true,
    event_state              varchar,
    event_title              VARCHAR UNIQUE NOT NULL,
    event_views              BIGINT,
    CONSTRAINT events_users_id_fk FOREIGN KEY (event_initiator_id) REFERENCES users (user_id),
    CONSTRAINT events_categories_id_fk FOREIGN KEY (event_category_id)  REFERENCES categories (category_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_requester_id BIGINT                                  NOT NULL,
    request_event_id     BIGINT                                  NOT NULL,
    request_created      TIMESTAMP DEFAULT now(),
    request_status       VARCHAR                             NOT NULL,
    CONSTRAINT request_requester_id_request_event_id_unique UNIQUE (request_requester_id, request_event_id),
    CONSTRAINT requests_users_id_fk FOREIGN KEY (request_requester_id) REFERENCES users (user_id),
    CONSTRAINT requests_events_id_fk FOREIGN KEY (request_event_id)  REFERENCES events (event_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_pinned BOOLEAN DEFAULT FALSE,
    compilation_title  VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT,
    event_id       BIGINT,
    CONSTRAINT events_compilations_event_id_compilation_id_pk PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT events_compilations_compilations_id_fk FOREIGN KEY (compilation_id) REFERENCES compilations (compilation_id),
    CONSTRAINT events_compilations_events_id_fk FOREIGN KEY (event_id) REFERENCES events (event_id)
);