CREATE TABLE IF NOT EXISTS stats (
    stat_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_app       VARCHAR NOT NULL,
    stat_uri       VARCHAR NOT NULL,
    stat_ip        VARCHAR NOT NULL,
    stat_timestamp TIMESTAMP NOT NULL);